framework:
    notifier:

        enabled: true

when@test:
    framework:
        notifier:

            chatter_transports:
                telegram: 'telegram://%env(string:default:grinway_telegram.bot.api_token:)%@default'
