framework:
    cache:
        pools:

            grinway_telegram.cache_pool.dop_end_figure:
                adapters:
                - 'cache.adapter.filesystem'
                default_lifetime: !php/const \PHP_INT_MAX
                tags: true
