grinway_telegram:
    # your-domain.com[:PORT]
    # Optional: used when executing command: php bin/console grinway_telegram:bot:set_webhook -d
    app_host: '%env(resolve:APP_HOST)%'

    bot:
        # Required
        name: '%env(APP_TELEGRAM_BOT_NAME)%'
        # Required
        api_token: '%env(APP_TELEGRAM_BOT_API_TOKEN)%'
        # Optional: When telegram supergroup topic message was sent you will get "is_topic_message" in the payload we heed to set "message_thread_id" equals to the "topic_id" from webhook payload, this option does this for you
        on_topic_supergroup_message_reply_directly_there: true

when@test:
    grinway_telegram:
        app_host: ~

        bot:
            # Required (when test becomes changed, because of you set here another value)
            name: '%env(APP_TEST_TELEGRAM_BOT_NAME)%'
            # Required (when test becomes changed, because of you set here another value)
            api_token: '%env(APP_TEST_TELEGRAM_BOT_API_TOKEN)%'
            # REQUIRED ONLY WHEN TEST
            chat_id: '%env(APP_TEST_TELEGRAM_BOT_CHAT_ID)%'
            # REQUIRED ONLY WHEN TEST
            payment_provider_token: '%env(APP_TEST_TELEGRAM_BOT_PAYMENT_PROVIDER_TOKEN)%'
