services:

    _defaults:
        autoconfigure: false
        autowire: true

    GrinWay\Telegram\Service\Telegram:
        class: 'GrinWay\Telegram\Service\Telegram'

    grinway_telegram: '@GrinWay\Telegram\Service\Telegram'
