grinway_telegram_bot_webhook:
    path: !php/const GrinWay\Telegram\Bot\Controller\TelegramController::WEBHOOK_PATH
    methods:
    - 'POST'
    controller: '.grinway_telegram.controller.bot_webhook'
